(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["FormalityTools`SmartTensor`"];


SmartTensor::usage="A smart tensor.";
SmartTensorQ::usage="";
Forget::usage="";
Pair::usage="";


Begin["`Private`"];





SmartTensor[tensor_,bases_]


SmartTensorQ[expr_,patt_:None,test_:None]:=Head[expr]===SmartTensor&&
If[patt=!=None,MatchQ[Depth[Forget[expr]]-1,patt],True]&&
If[test=!=None,And@@test/@Flatten[Forget[expr]],True];
MatrixQ[SmartTensor[t_,b_],opt___]^:=MatrixQ[t,opt]
ArrayQ[SmartTensor[t_,b_],opt___]^:=ArrayQ[t,opt]


Forget[SmartTensor[t_,b_]]^:=t


Flatten[SmartTensor[st__]]^:=Plus@@Times@@@Pair[SmartTensor[st]]


SmartTensor/:Pair[SmartTensor[t_,b_]]:=Transpose[{Flatten[t],Flatten[Outer[CircleTimes,##]&@@b]}]


SmartTensor/:Position[v_CircleTimes,SmartTensor[t_,b_]]:=Flatten[First@@@Position@@@Transpose[{b,v/.CircleTimes->List}],{1}]


SmartTensor/:Coefficient[v_CircleTimes,SmartTensor[t_,b_]]:=Part[t,##]&@@Position[v,SmartTensor[t,b]]


Needs["Combinatorica`"];


Transpose[SmartTensor[t_,b_],n_]^:=SmartTensor[Transpose[t,n],Permute[b,n]]


SmartTensor/:Plus[SmartTensor[t1_,b1_],SmartTensor[t2_,b2_]]:=If[b1===b2,SmartTensor[t1+t2,b1],Throw["Basis error"]]


SmartTensor/:Inner[f_,SmartTensor[t1_,b1_],SmartTensor[t2_,b2_],g_:Plus,n_:False]:=Module[{m},
If[!n,m=Length[b1],m=n];
If[t1[[m]]===t2[[1]],
SmartTensor[Inner[f,t1,t2,g,m],Join[Delete[b1,m],Delete[b2,1]]],
Throw["Basis error"]
]
]


SmartTensor/:Dot[tensors__SmartTensor]:=Inner[Times,tensors]


End[];
EndPackage[];



